services:
  postgres:
    image : postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  http-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/postgres

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - http-backend
      - ws-backend
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/postgres
      
  ws-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.websocket
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - http-backend
      
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/postgres
