FROM oven/bun:1

WORKDIR /app
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend   ./apps/http-backend
RUN bun install
RUN bun run prisma:generate
EXPOSE 8081
CMD ["bun", "run", "start:http-backend"]
