name: Deploy websocket
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.websocket
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/websocket:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/websocket:${{ github.sha }}

      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/websocket:latest
            sudo docker stop websocket || true
            sudo docker rm websocket || true
            sudo docker run -d --name websocket -p 8080:8080 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" ${{ secrets.DOCKERHUB_USERNAME }}/websocket:latest